# This file created by conda-build 25.7.0
# meta.yaml template originally from:
# C:\Users\task_175948882745887\openssl-feedstock\recipe, last modified Fri Oct  3 10:55:53 2025
# ------------------------------------------------

package:
  name: openssl
  version: 3.0.18
source:
  url: https://github.com/openssl/openssl/releases/download/openssl-3.0.18/openssl-3.0.18.tar.gz
  sha256: d80c34f5cf902dccf1f1b5df5ebb86d0392e37049e5d73df1b3abae72e4ffe8b
build:
  number: '0'
  run_exports:
    - openssl >=3.0.18,<4.0a0
  detect_binary_files_with_prefix: true
  binary_has_prefix_files: null
  string: h543e019_0
requirements:
  build:
    - nasm 2.16.03 h2f13f5f_0
    - perl 5.38.2.2 0_haa95532_strawberry
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.42 haa95532_5
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - vs2019_win-64 19.29.30159 hd50ca63_10
    - vs_win-64 2019.11 hd50ca63_10
    - vswhere 3.1.7 haa95532_0
  run:
    - ca-certificates
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30133
  host:
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
test:
  requires:
    - pkg-config
    - python 3.9.*
  commands:
    - copy NUL checksum.txt
    - openssl sha256 checksum.txt
    - openssl ecparam -name prime256v1
    - if "%SSL_CERT_FILE%"=="" exit 1
    - if not exist "%SSL_CERT_FILE%" exit 1
    - python -c "import urllib.request; urllib.request.urlopen('https://pypi.org')"
    - pkg-config --print-errors --exact-version "3.0.18" openssl
about:
  home: https://www.openssl.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  description: 'OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit

    for the Transport Layer Security (TLS) protocol formerly known as the

    Secure Sockets Layer (SSL) protocol. The protocol implementation is based

    on a full-strength general purpose cryptographic library, which can also

    be used stand-alone.

    '
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
extra:
  recipe-maintainers:
    - carlodri
    - chenghlee
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
  final: true
  copy_test_source_files: true
