# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.16.0
source:
  url: https://curl.se/download/curl-8.16.0.tar.bz2
  sha256: 9459180ab4933b30d0778ddd71c91fe2911fab731c46e59b3f4c8385b1596c91
build:
  run_exports:
    - libcurl >=8.16.0,<9.0a0
  ignore_run_exports:
    - libkrb5
  number: 0
  string: h97e0424_0
requirements:
  build:
    - vs2019_win-64 19.29.30159 hd50ca63_10
    - vs_win-64 2019.11 hd50ca63_10
    - vswhere 3.1.7 haa95532_0
  host:
    - ca-certificates 2025.9.9 haa95532_0
    - libkrb5 1.21.3 h885b0b7_4
    - libssh2 1.11.1 h2addb87_0
    - lz4-c 1.9.4 h2bbff1b_1
    - openssl 3.0.18 h543e019_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h500123d_2
    - zstd 1.5.6 h8880b57_0
  run:
    - libssh2 >=1.11.1
    - libssh2 >=1.11.1,<2.0a0
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30133
    - zlib >=1.2.13,<2.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - if exist %LIBRARY_BIN%\curl.exe exit 1
    - if not exist %LIBRARY_BIN%\libcurl.dll exit 1
    - if not exist %LIBRARY_LIB%\libcurl.lib exit 1
about:
  home: https://curl.se
  license: curl
  license_url: https://curl.se/docs/copyright.html
  license_family: MIT
  summary: tool and library for transferring data with URL syntax
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  doc_url: https://curl.se/docs
  dev_url: https://github.com/curl/curl
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  final: true
  copy_test_source_files: true
