# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: python
  version: 3.13.9
source:
  - url: https://www.python.org/ftp/python/3.13.9/Python-3.13.9.tar.xz
    sha256: ed5ef34cda36cfa2f3a340f07cac7e7814f91c7f3c411f6d3562323a866c5c66
    patches:
      - patches/0000-branding.patch
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      - patches/0009-Allow-cross-compiling-for-Darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0021-Override-configure-LIBFFI.patch
      - patches/0022-Unvendor-libmpdec.patch
build:
  number: 100
  activate_in_script: true
  no_link:
    - DLLs/_ctypes.pyd
  detect_binary_files_with_prefix: true
  string: h260b955_100_cp313
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.13.* *_cp313
  script_env:
    - CONDA_FORGE=no
    - PY_GIL_DISABLED=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  missing_dso_whitelist:
    - '**/MSVCR71.dll'
    - '**/MSVCR80.dll'
    - '**/api-ms-win-core-path-l1-1-0.dll'
requirements:
  build:
    - vs2019_win-64 19.29.30159 hd50ca63_10
    - vs_win-64 2019.11 hd50ca63_10
    - vswhere 3.1.7 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libmpdec-devel 4.0.0 haa95532_0
    - openssl 3.0.18 h543e019_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h500123d_2
  run:
    - bzip2 >=1.0.8,<2.0a0
    - expat >=2.7.1,<3.0a0
    - libffi >=3.4,<4.0a0
    - libmpdec >=4.0.0,<5.0a0
    - openssl >=3.0.18,<4.0a0
    - python_abi * *_cp313
    - sqlite >=3.50.2,<4.0a0
    - tk >=8.6.15,<8.7.0a0
    - tzdata
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30133
    - xz >=5.6.4,<6.0a0
    - zlib >=1.2.13,<2.0a0
test:
  requires:
    - cmake-no-system
    - ninja-base
    - ripgrep
    - vs2019_win-64
    - vs_win-64 2019.11.*
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/prefix-replacement/*
  commands:
    - echo on
    - set
    - python -V
    - pydoc -h
    - set "PIP_NO_BUILD_ISOLATION=False"
    - set "PIP_NO_DEPENDENCIES=True"
    - set "PIP_IGNORE_INSTALLED=True"
    - set "PIP_NO_INDEX=True"
    - set "PIP_CACHE_DIR=%CONDA_PREFIX%/pip_cache"
    - set "TEMP=%CONDA_PREFIX%/tmp"
    - mkdir "%TEMP%"
    - python -Im ensurepip --upgrade --default-pip
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv\\Scripts\\python.exe -c "import ctypes"
    - if exist %PREFIX%\\Scripts\\pydoc exit 1
    - if exist %PREFIX%\\Scripts\\idle exit 1
    - if not exist %PREFIX%\\Scripts\\pydoc-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\idle-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\idle.exe exit 1
    - if not exist %PREFIX%\\Scripts\\pydoc.exe exit 1
    - if not exist %PREFIX%\\include\\pyconfig.h exit 1
    - if not exist %PREFIX%\\libs\\python313.lib exit 1
    - pushd tests
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.13.9 --debug-find --trace --debug-output --debug-trycompile
      .
    - popd
    - popd
    - python run_test.py
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
about:
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_url: https://docs.python.org/3/license.html
  license_file: LICENSE
  summary: General purpose programming language
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  doc_url: https://www.python.org/doc/versions/
  dev_url: https://devguide.python.org/
extra:
  feedstock-name: python
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  skip-lints:
    - license_file_overspecified
  final: true
  copy_test_source_files: true
