# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# C:\Users\task_175758073895716\typer-feedstock\recipe, last modified Thu Sep 11 08:52:32 2025
# ------------------------------------------------

package:
  name: typer
  version: 0.17.4
source:
  url: https://pypi.org/packages/source/t/typer/typer-0.17.4.tar.gz
  sha256: b77dc07d849312fd2bb5e7f20a7af8985c7ec360c45b051ed5412f64d8dc1580
build:
  number: '0'
  script: C:\\miniconda3\\conda-bld\\typer_1757580777256\\_h_env\\python.exe -m pip
    install . -vv --no-deps --no-build-isolation
  entry_points:
    - typer = typer.cli:main
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.7.15 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.17 h35632f6_0
    - pdm-backend 2.4.3 py313h827c3e9_0
    - pip 25.2 pyhc872135_0
    - python 3.13.7 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 78.1.1 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - click >=8.0.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - rich >=10.11.0
    - shellingham >=1.3.0
    - typing-extensions >=3.7.4.3
test:
  source_files:
    - docs_src
    - tests
  imports:
    - typer
  commands:
    - pip check
    - typer --help
    - pytest -v tests  --deselect=tests/test_tutorial/test_multiple_values/test_arguments_with_multiple_values/test_tutorial001.py::test_main
      --deselect=tests/test_tutorial/test_parameter_types/test_number/test_tutorial001.py::test_invalid_score
      --deselect=tests/test_tutorial/test_parameter_types/test_number/test_tutorial001_an.py::test_invalid_score
  requires:
    - coverage
    - pip
    - pytest
about:
  home: https://github.com/tiangolo/typer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for building CLI applications
  description: 'Typer is library for building CLI applications that users will love
    using and developers will love creating. Based on Python 3.6+ type hints.


    The key features are:


    Intuitive to write: Great editor support. Completion everywhere. Less time debugging.
    Designed to be easy to use and learn. Less time reading docs.

    Easy to use: It''s easy to use for the final users. Automatic help, and automatic
    completion for all shells.

    Short: Minimize code duplication. Multiple features from each parameter declaration.
    Fewer bugs.

    Start simple: The simplest example adds only 2 lines of code to your app: 1 import,
    1 function call.

    Grow large: Grow in complexity as much as you want, create arbitrarily complex
    trees of commands and groups of subcommands, with options and arguments.

    '
  doc_url: https://typer.tiangolo.com
  dev_url: https://github.com/tiangolo/typer
extra:
  recipe-maintainers:
    - bollwyvl
    - dfornika
  final: true
  copy_test_source_files: true
