# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# C:\b\abs_393g1ayee_\clone\recipe, last modified Tue Jun 24 15:31:08 2025
# ------------------------------------------------

package:
  name: urllib3
  version: 2.5.0
source:
  url: https://pypi.io/packages/source/u/urllib3/urllib3-2.5.0.tar.gz
  sha256: 3fc47733c7e419d4bc3f6b3dc2b4f890bb743906a30d56ba4a5bfa4bbff92760
  patches:
    - patches/0001-remove-dummyserver-usage-in-tests.patch
build:
  number: '0'
  script: C:\\b\\abs_393g1ayee_\\croot\\urllib3_1750775481226\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313haa95532_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.2.25 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - hatch-vcs 0.4.0 py313haa95532_0
    - hatchling 1.27.0 py313haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - openssl 3.0.16 h3f729d1_0
    - packaging 24.2 py313haa95532_0
    - pathspec 0.10.3 py313haa95532_0
    - pip 25.1 pyhc872135_2
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.5 h286a616_100_cp313
    - python_abi 3.13 0_cp313
    - setuptools 78.1.1 py313haa95532_0
    - setuptools-scm 8.3.1 py313haa95532_1
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h5e9d12e_1
    - trove-classifiers 2024.10.14 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - vc 14.42 haa95532_5
    - vs2015_runtime 14.42.34433 hbfb602d_5
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - brotlicffi>=0.8.0
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - h2 >=4,<5
    - zstandard>=0.18.0
test:
  source_files:
    - dummyserver
    - test
  imports:
    - urllib.parse
    - urllib3
    - urllib3.connection
    - urllib3.contrib
    - urllib3.http2
    - urllib3.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('urllib3')=='2.5.0')"
    - cd test && pytest -v test_collections.py test_compatibility.py test_connection.py
      test_connectionpool.py test_exceptions.py test_fields.py test_filepost.py test_http2_connection.py
      test_no_ssl.py test_poolmanager.py test_proxymanager.py test_queue_monkeypatch.py
      test_response.py test_retry.py test_ssl.py test_util.py test_wait.py tz_stub.py
  requires:
    - h2 >=4,<5
    - pip
    - pytest >=8.3.4
    - trio >=0.27.0
    - trustme >=1.2.1
about:
  home: https://urllib3.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
    of the

    Python ecosystem already uses urllib3. urllib3 brings many critical features

    that are missing from the Python standard libraries, such as thread safety,

    connection pooling, client side ssl/tls verification, support for gzip and

    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

    and dealing with HTTP redirects.

    '
  doc_url: https://urllib3.readthedocs.io
  dev_url: https://github.com/urllib3/urllib3
extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - sethmlarson
    - sigmavirus24
  final: true
  copy_test_source_files: true
  sha: 0e800895d95672c32e111edc5f48d9be0a8210c9
  remote_url: git@github.com:AnacondaRecipes/urllib3-feedstock.git
  flow_run_id: 39e96c9a-e050-46e0-b98e-ddcc5fcdfcad
