#!/bin/sh
_CONDA_ROOT="C:\miniconda3\conda-bld\conda_1760457894461\_h_env"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
