# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176061365727698\typing-inspection-feedstock\recipe, last modified Thu Oct 16 11:29:20 2025
# ------------------------------------------------

package:
  name: typing-inspection
  version: 0.4.2
source:
  url: https://pypi.org/packages/source/t/typing-inspection/typing_inspection-0.4.2.tar.gz
  sha256: ba561c48a67c5958007083d386c3295464928b01faa735ab8547c5692e87f464
build:
  script: C:\\miniconda3\\conda-bld\\typing-inspection_1760614188477\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  number: '0'
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - hatchling 1.27.0 py313haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - packaging 25.0 py313haa95532_0
    - pathspec 0.12.1 py313haa95532_0
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.7 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing_extensions >=4.12.0
test:
  imports:
    - typing_inspection
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest . -v
  requires:
    - pip
    - pytest
about:
  summary: Runtime typing introspection tools
  home: https://github.com/pydantic/typing-inspection
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: 'A collection of runtime typing introspection tools, including a

    `typing_inspect` module that provides a consistent interface for

    inspecting types across different Python versions.

    '
  doc_url: https://pydantic.github.io/typing-inspection/0.4
  dev_url: https://github.com/pydantic/typing-inspection
extra:
  recipe-maintainers:
    - jan-janssen
  final: true
  copy_test_source_files: true
