# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# C:\b\abs_88e598m6o8\clone\recipe, last modified Tue Jul 29 08:36:33 2025
# ------------------------------------------------

package:
  name: tomli
  version: 2.2.1
source:
  url: https://pypi.io/packages/source/t/tomli/tomli-2.2.1.tar.gz
  sha256: cd45e1dc79c835ce60f7404ec8119f2eb06d38b1deba146f07ced3bbc44505ff
build:
  number: '0'
  script: C:\\b\\abs_88e598m6o8\\croot\\tomli_1753774604115\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.2.25 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - flit-core 3.9.0 py313hcda33d2_1
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - openssl 3.0.17 h35632f6_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h286a616_100_cp313
    - python_abi 3.13 0_cp313
    - setuptools 78.1.1 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.14 h5e9d12e_1
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  imports:
    - tomli
  files:
    - example.toml
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('tomli')=='2.2.1')"
about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  description: Tomli is a Python library for parsing TOML. It is fully compatible
    with TOML v1.0.0.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/hukkin/tomli
  doc_url: https://github.com/hukkin/tomli/blob/master/README.md
extra:
  recipe-maintainers:
    - thewchan
  final: true
  copy_test_source_files: true
  sha: 69323bd5dfccc885317e49e70b6582797af8ed65
  remote_url: git@github.com:AnacondaRecipes/tomli-feedstock.git
  flow_run_id: 88531934-1764-4bc8-bfc4-5afb83150732
