# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176174499110558\annotated-types-feedstock\recipe, last modified Wed Oct 29 13:37:58 2025
# ------------------------------------------------

package:
  name: annotated-types
  version: 0.6.0
source:
  url: https://pypi.org/packages/source/a/annotated_types/annotated_types-0.6.0.tar.gz
  sha256: 563339e807e53ffd9c267e99fc6d9ea23eb8443c08f112651963e24e22f84a5d
build:
  script: C:\\miniconda3\\conda-bld\\annotated-types_1761745107361\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  number: '1'
  string: py313haa95532_1
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - hatchling 1.27.0 py313haa95532_1
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - packaging 25.0 py313haa95532_1
    - pathspec 0.12.1 py313haa95532_0
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.9 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  source_files:
    - tests
  imports:
    - annotated_types
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
about:
  home: https://github.com/annotated-types/annotated-types
  summary: Reusable constraint types to use with typing.Annotated
  description: 'This package provides metadata objects which can be used to represent
    common constraints such as upper and lower

    bounds on scalar values and collection sizes, a Predicate marker for runtime checks,
    and descriptions of how we

    intend these metadata to be interpreted. In some cases, we also note alternative
    representations which do not

    require this package.

    '
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/annotated-types/annotated-types
  dev_url: https://github.com/annotated-types/annotated-types
extra:
  recipe-maintainers:
    - Zac-HD
    - mattwthompson
    - samuelcolvin
  final: true
  copy_test_source_files: true
