# This file created by conda-build 25.7.0
# meta.yaml template originally from:
# C:\Users\task_175878423045932\pydantic-settings-feedstock\recipe, last modified Thu Sep 25 07:10:43 2025
# ------------------------------------------------

package:
  name: pydantic-settings
  version: 2.10.1
source:
  url: https://pypi.org/packages/source/p/pydantic-settings/pydantic_settings-2.10.1.tar.gz
  sha256: 06f0062169818d0f5524420a360d632d5857b83cffd4d42fe29597807a1614ee
build:
  number: '0'
  script: C:\\miniconda3\\conda-bld\\pydantic-settings_1758784270277\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - hatchling 1.27.0 py313haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.17 h35632f6_0
    - packaging 25.0 py313haa95532_0
    - pathspec 0.12.1 py313haa95532_0
    - pip 25.2 pyhc872135_0
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.7 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 78.1.1 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - pydantic >=2.7.0
    - python >=3.13,<3.14.0a0
    - python-dotenv >=0.21.0
    - python_abi 3.13.* *_cp313
    - typing-inspection >=0.4.0
  run_constrained:
    - azure-identity >=1.16.0
    - azure-keyvault-secrets >=4.8.0
    - boto3>=1.35.0
    - google-cloud-secret-manager>=2.23.1
    - pyyaml >=6.0.1
    - tomli >=2.0.1
test:
  source_files:
    - tests
  imports:
    - pydantic_settings
  commands:
    - pip check
    - pytest -v tests --ignore=tests/test_docs.py
  requires:
    - pip
    - pytest
    - pytest-mock
about:
  home: https://github.com/pydantic/pydantic-settings
  summary: Settings management using Pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: 'Pydantic Settings provides optional Pydantic features for loading
    a settings or config class from environment

    variables or secrets files.

    '
  dev_url: https://github.com/pydantic/pydantic-settings
  doc_url: https://docs.pydantic.dev/latest/usage/pydantic_settings
extra:
  recipe-maintainers:
    - fhoehle
    - jan-janssen
  final: true
  copy_test_source_files: true
