# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# C:\b\abs_a1jv6v_pzp\clone\recipe, last modified Mon Feb 24 14:41:57 2025
# ------------------------------------------------

package:
  name: jaraco.functools
  version: 4.1.0
source:
  sha256: 70f7e0e2ae076498e212562325e805204fc092d7b4c17e0e86c959e249701a9d
  url: https://pypi.org/packages/source/j/jaraco.functools/jaraco_functools-4.1.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_a1jv6v_pzp\\croot\\jaraco.functools_1740408129620\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.12.31 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - openssl 3.0.15 h827c3e9_0
    - packaging 24.2 py313haa95532_0
    - pip 25.0 py313haa95532_0
    - python 3.13.2 hadb2040_100_cp313
    - python_abi 3.13 0_cp313
    - setuptools 75.8.0 py313haa95532_0
    - setuptools-scm 8.1.0 py313haa95532_0
    - setuptools_scm 8.1.0 hd3eb1b0_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025a h04d1e81_0
    - vc 14.42 haa95532_4
    - vs2015_runtime 14.42.34433 he0abc0d_4
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - more-itertools
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -vv test_functools.py -k "not test_function_throttled"
  imports:
    - jaraco.functools
  requires:
    - jaraco.classes
    - pip
    - pytest
  source_files:
    - test_functools.py
about:
  dev_url: https://github.com/jaraco/jaraco.functools
  doc_url: https://github.com/jaraco/jaraco.functools
  home: https://github.com/jaraco/jaraco.functools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional functools in the spirit of stdlib's functools.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a1a9b5ec-d5e7-432f-9de5-954171be476f
  recipe-maintainers:
    - carlodri
  remote_url: git@github.com:AnacondaRecipes/jaraco.functools-feedstock.git
  sha: 3d4fd6597492367b8e219648b4baf7f8be3583c8
