# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# C:\b\abs_e4z9s4yute\clone\recipe, last modified Tue Aug 12 10:27:24 2025
# ------------------------------------------------

package:
  name: fmt
  version: 11.2.0
source:
  url: https://github.com/fmtlib/fmt/archive/11.2.0.tar.gz
  sha256: bc23066d87ab3168f27cef3e97d545fa63314f5c79df5ea444d41d56f962c6af
  patches: null
build:
  number: '0'
  run_exports:
    - fmt >=11.2.0,<12.0a0
  string: h58b7f6e_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - cmake 3.31.2 h53b1909_0
    - libuv 1.48.0 h827c3e9_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja-base 1.12.1 h4157e71_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - vs2019_win-64 19.29.30159 hd50ca63_10
    - vs_win-64 2019.11 hd50ca63_10
    - vswhere 2.8.4 haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.6 h8880b57_0
  host:
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30133
test:
  commands:
    - if exist %LIBRARY_PREFIX%\include\fmt\core.h (exit 0) else (exit 1)
    - if exist %LIBRARY_PREFIX%\include\fmt\format.h (exit 0) else (exit 1)
    - if exist %LIBRARY_PREFIX%\lib\cmake\fmt-config.cmake (exit 0) else (exit 1)
    - if exist %LIBRARY_PREFIX%\bin\fmt.dll (exit 0) else (exit 1)
about:
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
extra:
  recipe-maintainers:
    - saraedum
    - tdegeus
    - vitaut
  final: true
  copy_test_source_files: true
  sha: ceadd42ef69ddf5d1934eb9a0bd90aeb330fcaa9
  remote_url: git@github.com:AnacondaRecipes/fmt-feedstock.git
  flow_run_id: e476667f-afc1-472f-b2c5-cad96945df0d
