# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176229492864674\anaconda-cli-base-feedstock\recipe, last modified Tue Nov  4 22:23:29 2025
# ------------------------------------------------

package:
  name: anaconda-cli-base
  version: 0.6.0
source:
  url: https://pypi.org/packages/source/a/anaconda-cli-base/anaconda_cli_base-0.6.0.tar.gz
  sha256: da0a8278ba4b9766e0df01fc8b15e8c2d1030c7229c51adddf3f0e84430601f2
  patches:
    - 0001-windows-path-fix.patch
build:
  number: '0'
  script: C:\\miniconda3\\conda-bld\\anaconda-cli-base_1762295036999\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - anaconda = anaconda_cli_base.cli:app
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.11.4 haa95532_0
    - expat 2.7.3 h9214b88_0
    - hatch-vcs 0.4.0 py313haa95532_1
    - hatchling 1.27.0 py313haa95532_1
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - packaging 25.0 py313haa95532_1
    - pathspec 0.12.1 py313haa95532_1
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.9 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - setuptools-scm 8.3.1 py313haa95532_1
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - click <8.2
    - packaging >=23.0
    - pydantic-settings >=2.3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - readchar
    - rich
    - tomli
    - typer
  run_constrained:
    - anaconda-client >=1.13.0
    - anaconda-cloud-cli >=0.3.0
test:
  source_files:
    - tests
  imports:
    - anaconda_cli_base
  requires:
    - pip
    - pytest
    - pytest-mock
    - types-requests
  commands:
    - pip check
    - anaconda -h
    - anaconda -V
    - python -c "from anaconda_cli_base import __version__; assert __version__ ==
      \"0.6.0\""
    - python -c "from importlib.metadata import version; assert(version('anaconda-cli-base')=='0.6.0')"
    - pytest -v tests
about:
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  dev_url: https://pypi.org/project/anaconda-cli-base
  doc_url: https://pypi.org/project/anaconda-cli-base
extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
  final: true
  copy_test_source_files: true
