# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176115174002271\libarchive-feedstock\recipe, last modified Wed Oct 22 16:49:16 2025
# ------------------------------------------------

package:
  name: libarchive
  version: 3.8.2
source:
  url: https://github.com/libarchive/libarchive/releases/download/v3.8.2/libarchive-3.8.2.tar.gz
  sha256: 5f2d3c2fde8dc44583a61165549dc50ba8a37c5947c90fc02c8e5ce7f1cfb80d
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
build:
  number: '0'
  run_exports:
    - libarchive >=3.8.2,<3.9.0a0
  string: h6c023e8_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - cmake 4.1.2 hc6e6e83_0
    - libuv 1.48.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja-base 1.12.1 h4157e71_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - vs2019_win-64 19.29.30159 hd50ca63_10
    - vs_win-64 2019.11 hd50ca63_10
    - vswhere 3.1.7 haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
    - zstd 1.5.7 h56299aa_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - libiconv 1.16 h2bbff1b_3
    - libxml2 2.13.8 h866ff63_0
    - lz4-c 1.9.4 h2bbff1b_1
    - openssl 3.0.18 h543e019_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h500123d_2
    - zstd 1.5.6 h8880b57_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libiconv >=1.16,<2.0a0
    - libxml2 >=2.13.8,<2.14.0a0
    - lz4-c >=1.9.4,<1.10.0a0
    - openssl >=3.0.18,<4.0a0
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30133
    - xz >=5.6.4,<6.0a0
    - zlib >=1.2.13,<2.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  requires:
    - ripgrep
  files:
    - test-archives/archive.7z
    - test-archives/hello_world.tar.zst
    - test-archives/hello_world.xar
  commands:
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - pushd test-archives
    - bsdtar -vxf hello_world.xar 2>&1 | rg "x hello_world"
    - bsdtar -vxf archive.7z 2>&1 | rg "x 7zip-archive"
    - bsdtar -vxf hello_world.tar.zst 2>&1 | rg "greets"
    - popd
about:
  home: https://libarchive.org
  license: BSD-2-Clause
  license_file: COPYING
  license_family: BSD
  summary: Multi-format archive and compression library
  description: 'Libarchive is an open-source BSD-licensed C programming library that
    provides streaming access

    to a variety of different archive formats, including tar, cpio, pax, Zip, and
    ISO9660 images.

    The distribution also includes bsdtar and bsdcpio, full-featured implementations
    of tar and cpio

    that use libarchive.

    When reading archives, libarchive uses a robust automatic format detector that
    can automatically handle archives

    that have been compressed with gzip, bzip2, xz, lzip, and several other popular
    compression algorithms.

    '
  dev_url: https://github.com/libarchive/libarchive
  doc_url: https://github.com/libarchive/libarchive/wiki
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
  final: true
  copy_test_source_files: true
