# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176235658680233\platformdirs-feedstock\recipe, last modified Wed Nov  5 15:29:56 2025
# ------------------------------------------------

package:
  name: platformdirs
  version: 4.5.0
source:
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-4.5.0.tar.gz
  sha256: 70ddccdd7c99fc5942e9fc25636a8b34d04c24b335100223152c2803e4063312
build:
  number: '0'
  script: C:\\miniconda3\\conda-bld\\platformdirs_1762356623609\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.11.4 haa95532_0
    - expat 2.7.3 h9214b88_0
    - hatch-vcs 0.5.0 py313haa95532_0
    - hatchling 1.27.0 py313haa95532_1
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - packaging 25.0 py313haa95532_1
    - pathspec 0.12.1 py313haa95532_1
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313haa95532_0
    - python 3.13.9 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - setuptools-scm 8.3.1 py313haa95532_1
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py313haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  source_files:
    - tests
  imports:
    - platformdirs
  requires:
    - appdirs
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    - pytest tests -vv
about:
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: 'About A small Python module for determining appropriate

    platform-specific dirs, e.g. a "user data dir".

    '
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io
extra:
  recipe-maintainers:
    - adament
    - gaborbernat
  final: true
  copy_test_source_files: true
