# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176175237924352\pysocks-feedstock\recipe, last modified Wed Oct 29 15:50:03 2025
# ------------------------------------------------

package:
  name: pysocks
  version: 1.7.1
source:
  url: https://pypi.org/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
  sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
build:
  number: '1'
  script: C:\\miniconda3\\conda-bld\\pysocks_1761753030965\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py313haa95532_1
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - pip 25.2 pyhc872135_1
    - python 3.13.9 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - win_inet_pton
test:
  imports:
    - socks
about:
  home: https://github.com/Anorov/PySocks
  license_file: LICENSE
  license: BSD 3-Clause
  summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
    more information.
  license_family: BSD
  doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
  dev_url: https://github.com/Anorov/PySocks
extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
  final: true
  copy_test_source_files: true
