# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176037559835019\rich-feedstock\recipe, last modified Mon Oct 13 17:13:54 2025
# ------------------------------------------------

package:
  name: rich
  version: 14.2.0
source:
  url: https://github.com/Textualize/rich/archive/refs/tags/v14.2.0.tar.gz
  sha256: 589ddd6a66adbffb9d0e406da9d529a886d2c040177da4b72fad4a8563ff5afc
build:
  number: '0'
  script: C:\\miniconda3\\conda-bld\\rich_1760375661587\\_h_env\\python.exe -m pip
    install . --no-deps --no-build-isolation -vv
  string: py313haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.9.9 haa95532_0
    - expat 2.7.1 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.0.18 h543e019_0
    - pip 25.2 pyhc872135_0
    - poetry-core 2.2.0 py313haa95532_0
    - python 3.13.7 h260b955_100_cp313
    - python_abi 3.13 1_cp313
    - setuptools 80.9.0 py313haa95532_0
    - sqlite 3.50.2 hda9a48d_1
    - tk 8.6.15 hf199647_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.45.1 py313haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
  run:
    - markdown-it-py >=2.2.0
    - pygments >=2.13.0,<3.0.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - ipywidgets >=7.5.1,<9
test:
  imports:
    - rich
  source_files:
    - tests
  commands:
    - pip check
    - pytest -vv tests -k "not (test_markdown_render or test_syntax_highlight_ranges
      or test_option_no_wrap or test_python_render or test_card_render or test_brokenpipeerror
      or test_background_color_override_includes_padding)"
  requires:
    - attrs
    - pip
    - pytest
about:
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the
    terminal.
  description: "Rich is a Python library for rich text and beautiful formatting\n\
    in the terminal.The Rich API makes it easy to add color and style to\nterminal\
    \ output. Rich can also render pretty tables, progress bars,\nmarkdown, syntax\
    \ highlighted source code, tracebacks, and more \u2014 out\nof the box.\n"
  doc_url: https://rich.readthedocs.io
  dev_url: https://github.com/Textualize/rich
extra:
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
  final: true
  copy_test_source_files: true
